-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.exchange_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  base_currency character varying NOT NULL,
  target_currency character varying NOT NULL,
  rate numeric NOT NULL CHECK (rate > 0::numeric),
  source character varying DEFAULT 'manual'::character varying,
  valid_from timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['payment'::character varying, 'renewal'::character varying, 'expiry'::character varying, 'system'::character varying, 'reminder'::character varying]::text[])),
  title character varying NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])),
  category character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  scheduled_for timestamp with time zone,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notifications_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.payment_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid,
  service_name character varying NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  currency character varying NOT NULL CHECK (currency::text = ANY (ARRAY['KRW'::character varying, 'USD'::character varying]::text[])),
  payment_date date NOT NULL,
  payment_method character varying,
  payment_cycle character varying CHECK (payment_cycle::text = ANY (ARRAY['monthly'::character varying, 'yearly'::character varying, 'onetime'::character varying]::text[])),
  status character varying DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_history_pkey PRIMARY KEY (id),
  CONSTRAINT payment_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payment_history_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.subscription_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name character varying NOT NULL,
  color character varying DEFAULT '#3B82F6'::character varying,
  icon character varying,
  description text,
  is_default boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_categories_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  service_name character varying NOT NULL,
  service_url text,
  logo character varying,
  logo_image text,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  currency character varying NOT NULL CHECK (currency::text = ANY (ARRAY['KRW'::character varying, 'USD'::character varying]::text[])),
  payment_cycle character varying NOT NULL CHECK (payment_cycle::text = ANY (ARRAY['monthly'::character varying, 'yearly'::character varying, 'onetime'::character varying]::text[])),
  payment_day integer NOT NULL CHECK (payment_day >= 1 AND payment_day <= 31),
  payment_method character varying,
  start_date date NOT NULL,
  end_date date,
  auto_renewal boolean DEFAULT true,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'paused'::character varying, 'cancelled'::character varying]::text[])),
  category character varying,
  tier character varying,
  tags ARRAY DEFAULT '{}'::text[],
  memo text,
  notifications jsonb DEFAULT '{"same_day": true, "seven_days": true, "three_days": true}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  total_subscriptions integer DEFAULT 0,
  active_subscriptions integer DEFAULT 0,
  paused_subscriptions integer DEFAULT 0,
  cancelled_subscriptions integer DEFAULT 0,
  monthly_total_krw numeric DEFAULT 0,
  yearly_total_krw numeric DEFAULT 0,
  average_monthly_krw numeric DEFAULT 0,
  year integer NOT NULL,
  month integer NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT user_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  exchange_rate numeric DEFAULT 1300.00,
  default_currency character varying DEFAULT 'KRW'::character varying CHECK (default_currency::text = ANY (ARRAY['KRW'::character varying, 'USD'::character varying]::text[])),
  notifications jsonb DEFAULT '{"sms": false, "push": true, "email": true, "same_day": true, "seven_days": true, "three_days": true, "price_changes": false, "payment_reminders": true, "subscription_expiry": true}'::jsonb,
  theme character varying DEFAULT 'dark'::character varying CHECK (theme::text = ANY (ARRAY['light'::character varying, 'dark'::character varying, 'auto'::character varying]::text[])),
  language character varying DEFAULT 'ko'::character varying CHECK (language::text = ANY (ARRAY['ko'::character varying, 'en'::character varying]::text[])),
  timezone character varying DEFAULT 'Asia/Seoul'::character varying,
  date_format character varying DEFAULT 'YYYY-MM-DD'::character varying,
  currency_format character varying DEFAULT '₩#,##0'::character varying,
  music_enabled boolean DEFAULT true,
  sound_effects boolean DEFAULT true,
  auto_backup boolean DEFAULT true,
  data_retention_days integer DEFAULT 365,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);